[workspace]
members = ["core/*", "crypto/*"]
resolver = "2"

[workspace.package]
version = "1.1.1-Alpha3"
edition = "2024"
authors = ["Q. T. Felix <qtfelix@qu4nt.space>"]
license = "MIT LICENSE"

[profile.release]
strip = true

[workspace.dependencies]
entlib-native-helper = { path = "./core/helper", version = "1.1.1-Alpha3" }
entlib-native-ffi = { path = "./core/ffi", version = "1.1.1-Alpha3" }
entlib-native-sha2 = { path = "./crypto/sha2", version = "1.1.1-Alpha3" }
entlib-native-sha3 = { path = "./crypto/sha3", version = "1.1.1-Alpha3" }
entlib-native-rng = { path = "./crypto/rng", version = "1.1.1-Alpha3" }