[workspace]
members = ["internal/*", "crypto/*"]
resolver = "2"

[workspace.package]
version = "1.1.2-Alpha"
edition = "2024"
authors = ["Q. T. Felix <qtfelix@qu4nt.space>"]
license = "MIT LICENSE"

[profile.release]
strip = true

[workspace.dependencies]
### INTERNAL CORE DEPENDENCIES ###
entlib-native-ffi =             { path = "./internal/ffi",            version = "1.1.2-Alpha" }
entlib-native-quantum-util =    { path = "./internal/quantum-util",   version = "1.1.2-Alpha" }
### INTERNAL CRYPTO DEPENDENCIES ###
entlib-native-base64 =          { path = "./crypto/base64",           version = "1.1.2-Alpha" }
entlib-native-constant-time =   { path = "./crypto/constant-time",    version = "1.1.2-Alpha" }
entlib-native-core-secure =     { path = "./crypto/core-secure",      version = "1.1.2-Alpha" }
entlib-native-rng =             { path = "./crypto/rng",              version = "1.1.2-Alpha" }
entlib-native-sha2 =            { path = "./crypto/sha2",             version = "1.1.2-Alpha" }
entlib-native-sha3 =            { path = "./crypto/sha3",             version = "1.1.2-Alpha" }
