[package]
name = "entlib-native"
version = "1.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
hex = "0.4.3"
libcrux-ml-dsa = "0.0.5"
libcrux-ml-kem = "0.0.5"
rand = "0.9.2"
rand_chacha = "0.9.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sha2 = "0.10.8"
sha3 = "0.10.8"
x25519-dalek = { version = "2.0.1", features = ["static_secrets"] }
zeroize = "1.8.2"
