[workspace]
members = ["core/*"]
resolver = "2"

[workspace.package]
version = "1.1.1-Alpha2"
edition = "2024"
authors = ["Q. T. Felix <qtfelix@qu4nt.space>"]
license = "MIT LICENSE"

[profile.release]
strip = true

[workspace.dependencies]
entlib-native-helper = { path = "./core/helper", version = "1.1.1-Alpha2" }
entlib-native-crypto = { path = "./core/crypto", version = "1.1.1-Alpha2" }
entlib-native-ffi = { path = "./core/ffi", version = "1.1.1-Alpha2" }